export { default as Home } from './Home'
export { default as About } from './About'
export { default as RoadMap } from './RoadMap'
export { default as FAQ } from './FAQ'
export { default as Team } from './Team'
export { default as Showcase } from './Showcase'